# app and server related properties
server:
  port: 8761

# app related properties
spring:
  application:
    name: eureka-discovery

# Properties needed for Eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
