# fetch properties from config server
spring:
  application:
    name: auth-service
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:9090/
    name: auth-service
